definitions:

  config:
    type: :system/system.t:system_config
    value:
      services:
        :system/system:adapter_creg.service: adapter_creg.config
        :system/system:service_creg.service: service_creg.config
        :system/system:service_config_creg.service: service_config_creg.config
        :transport/transport:transport.service: transport.config
        :transport/registries:peer_creg.service: peer_creg.config
        :transport/registries:signature_creg.service: signature_creg.config
        :transport/registries:parcel_creg.service: parcel_creg.config

  adapter_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :system/adapter.t:config_adapter: :system/adapter:config_adapter.actor
        :system/adapter.t:service_args_adapter: :system/adapter:service_args_adapter.actor
        :system/adapter.t:service_object_adapter: :system/adapter:service_object_adapter.actor

  service_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :system/system.t:service_config_creg: :system/system:service_config_creg.service-actor
        :system/resolving_code_registry:system_code_registry_factory.service.t: :system/resolving_code_registry:system_code_registry_factory.service-actor
        :pick_refs:pick_refs.service.t: :pick_refs:pick_refs.service-actor
        :pick_refs:pick_refs_cache.service.t: :pick_refs:pick_refs_cache.service-actor
        :bundler:bundler.service.t: :bundler:bundler.service-actor
        :transport/selectors:selectors.service.t: :transport/selectors:selectors.service-actor
        :transport/transport:transport.service.t: :transport/transport:transport.service-actor
        :transport/registries:peer_creg.service.t: :transport/registries:peer_creg.service-actor
        :transport/registries:signature_creg.service.t: :transport/registries:signature_creg.service-actor
        :transport/registries:parcel_creg.service.t: :transport/registries:parcel_creg.service-actor
        :transport/rsa:generate_rsa_identity.service.t: :transport/rsa:generate_rsa_identity.service-actor
        worker_main:subprocess_worker_main.service.t: worker_main:subprocess_worker_main.service-actor

  service_config_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :transport/registries:identity_creg.service.t: :system/config:TypedDictConfigCtl.from_service_piece.actor
        :transport/registries:peer_creg.service.t: :system/config:TypedDictConfigCtl.from_service_piece.actor
        :transport/registries:signature_creg.service.t: :system/config:TypedDictConfigCtl.from_service_piece.actor
        :transport/registries:parcel_creg.service.t: :system/config:TypedDictConfigCtl.from_service_piece.actor
        :transport/transport:transport.service.t: :system/config:RecordConfigCtl.from_service_piece.actor

  transport.config:
    type: :transport/transport.t:config
    value:
      message_size_limit: null

  peer_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :transport/rsa.t:rsa_peer: :transport/rsa:RsaPeer.from_piece.actor

  signature_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :transport/rsa.t:rsa_signature: :transport/rsa:RsaSignature.from_piece.actor

  parcel_creg.config:
    type: :system/system.t:typed_item_list
    value:
      items:
        :transport/rsa.t:rsa_parcel: :transport/rsa:RsaParcel.from_piece.actor
