import:
- client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
- lcs.lcs_view.config:bool_1
- lcs.lcs_view.config:column_d_4
- lcs.lcs_view.config:list_d_1
- lcs.lcs_view.config:show_d_1
- legacy_type.builtin:string
- legacy_type.column:column_d
- legacy_type.lcs_resource_storage:mapping
- legacy_type.view_factory_list:view
- ui.view.view_factory_list:open_view_factory_list.d
definitions:
  column_d_1:
    type: legacy_type.column:column_d
    value:
      name: view_t
  column_d_2:
    type: legacy_type.column:column_d
    value:
      name: system_fn
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - ui.view.view_factory_list:open_view_factory_list.d
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_Alt_F
      - key:
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        - legacy_type.view_factory_list:view
        - lcs.lcs_view.config:column_d_4
        value: lcs.lcs_view.config:bool_1
      - key:
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        - legacy_type.view_factory_list:view
        - column_d_1
        value: lcs.lcs_view.config:bool_1
      - key:
        - column_d_2
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        - legacy_type.view_factory_list:view
        value: lcs.lcs_view.config:bool_1
  shortcut_Alt_F:
    type: legacy_type.builtin:string
    value: Alt+F
