import:
- lcs.lcs_view.config:bool_1
- lcs.lcs_view.config:list_d
- lcs.lcs_view.config:show_d
- legacy_type.global_commands:view
- legacy_type.lcs_resource_storage:mapping
- models.model_commands.config:column_d_1
- models.model_commands.config:column_d_2
- models.model_commands.config:column_d_3
definitions:
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - models.model_commands.config:column_d_1
        - lcs.lcs_view.config:show_d
        - lcs.lcs_view.config:list_d
        - legacy_type.global_commands:view
        value: lcs.lcs_view.config:bool_1
      - key:
        - models.model_commands.config:column_d_2
        - lcs.lcs_view.config:show_d
        - lcs.lcs_view.config:list_d
        - legacy_type.global_commands:view
        value: lcs.lcs_view.config:bool_1
      - key:
        - lcs.lcs_view.config:show_d
        - lcs.lcs_view.config:list_d
        - models.model_commands.config:column_d_3
        - legacy_type.global_commands:view
        value: lcs.lcs_view.config:bool_1
