import:
- legacy_type.builtin:bool
- legacy_type.column:column_d
- legacy_type.column:list_d
- legacy_type.column:show_d
- legacy_type.lcs_resource_storage:mapping
- legacy_type.model_commands:model
definitions:
  bool_1:
    type: legacy_type.builtin:bool
    value: false
  column_d_1:
    type: legacy_type.column:column_d
    value:
      name: ui_command_d
  column_d_2:
    type: legacy_type.column:column_d
    value:
      name: model_command_d
  column_d_3:
    type: legacy_type.column:column_d
    value:
      name: repr
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - legacy_type.model_commands:model
        - column_d_1
        - show_d_1
        - list_d_1
        value: bool_1
      - key:
        - column_d_2
        - legacy_type.model_commands:model
        - show_d_1
        - list_d_1
        value: bool_1
      - key:
        - legacy_type.model_commands:model
        - show_d_1
        - list_d_1
        - column_d_3
        value: bool_1
  list_d_1:
    type: legacy_type.column:list_d
    value: {}
  show_d_1:
    type: legacy_type.column:show_d
    value: {}
