import:
- lcs.lcs_view.config:bool_1
- lcs.lcs_view.config:list_d_1
- lcs.lcs_view.config:show_d_1
- legacy_type.column:column_d
- legacy_type.lcs_resource_storage:mapping
- legacy_type.model_commands:model
definitions:
  column_d_1:
    type: legacy_type.column:column_d
    value:
      name: ui_command_d
  column_d_2:
    type: legacy_type.column:column_d
    value:
      name: model_command_d
  column_d_3:
    type: legacy_type.column:column_d
    value:
      name: repr
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - legacy_type.model_commands:model
        - column_d_1
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        value: lcs.lcs_view.config:bool_1
      - key:
        - column_d_2
        - legacy_type.model_commands:model
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        value: lcs.lcs_view.config:bool_1
      - key:
        - legacy_type.model_commands:model
        - lcs.lcs_view.config:show_d_1
        - lcs.lcs_view.config:list_d_1
        - column_d_3
        value: lcs.lcs_view.config:bool_1
