definitions:

  config.module:
    type: builtin:type:python_module
    value:
      module_name: config
      file_name: config.dyn.py
      imports:
        pyobj:
          htypes.system.typed_item: system.t:typed_item
          htypes.system.typed_item_list: system.t:typed_item_list
          htypes.system.data_item: system.t:data_item
          htypes.system.data_item_list: system.t:data_item_list
          services.pyobj_creg: builtin:service:pyobj_creg
          services.web: builtin:service:web
        raw: {}

  RecordConfigCtl:
    type: builtin:type:attribute
    value:
      object: config.module
      attr_name: RecordConfigCtl

  RecordConfigCtl.from_service_piece:
    type: builtin:type:attribute
    value:
      object: RecordConfigCtl
      attr_name: from_service_piece

  RecordConfigCtl.from_service_piece.actor:
    type: system.t:service_actor
    value:
      fn: RecordConfigCtl.from_service_piece
      adapters: []

  TypedDictConfigCtl:
    type: builtin:type:attribute
    value:
      object: config.module
      attr_name: TypedDictConfigCtl

  TypedDictConfigCtl.from_config_piece:
    type: builtin:type:attribute
    value:
      object: TypedDictConfigCtl
      attr_name: from_config_piece

  TypedDictConfigCtl.from_config_piece.actor:
    type: system.t:service_actor
    value:
      fn: TypedDictConfigCtl.from_config_piece
      adapters: []

  TypedDictConfigCtl.from_service_piece:
    type: builtin:type:attribute
    value:
      object: TypedDictConfigCtl
      attr_name: from_service_piece

  TypedDictConfigCtl.from_service_piece.actor:
    type: system.t:service_actor
    value:
      fn: TypedDictConfigCtl.from_service_piece
      adapters: []
