import:
- legacy_type.builtin:python_module
- legacy_type.system:actor_value_ctl
- legacy_type.system:data_value_ctl

definitions:

  config_value_ctl.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_value_ctl
      file_name: config_value_ctl.dyn.py
      import_list:
        htypes.system.actor_value_ctl: legacy_type.system:actor_value_ctl
        htypes.system.data_value_ctl: legacy_type.system:data_value_ctl
