import:
- builtin:type:python_module
- system.t:list_struct_ctl
- system.t:single_struct_ctl

definitions:

  config_struct_ctl.module:
    type: builtin:type:python_module
    value:
      module_name: config_struct_ctl
      file_name: config_struct_ctl.dyn.py
      imports:
        pyobj:
          htypes.system.list_struct_ctl: system.t:list_struct_ctl
          htypes.system.single_struct_ctl: system.t:single_struct_ctl
        raw: {}
