definitions:

  config_layer.module:
    type: builtin:type:python_module
    value:
      module_name: config_layer
      file_name: config_layer.dyn.py
      imports:
        pyobj:
          services.code_registry_ctr: builtin:service:code_registry_ctr
          services.deduce_t: builtin:service:deduce_t
          services.mosaic: builtin:service:mosaic
          services.web: builtin:service:web
          htypes.builtin.record_mt: builtin:type:record_mt
          htypes.system.service_config: system.t:service_config
          htypes.system.system_config: system.t:system_config
        raw: {}

  resource_name_creg:
    type: builtin:type:attribute
    value:
      object: config_layer.module
      attr_name: resource_name_creg

  resource_name_creg.service:
    type: system.t:service_template
    value:
      name: resource_name_creg
      ctl: actor_dict.config_ctl
      function: resource_name_creg
      service_params: []
      want_config: true
      free_params: []

  one_way.key_ctl:
    type: system.t:one_way_key_ctl
    value: {}

  actor.value_ctl:
    type: system.t:actor_value_ctl
    value: {}

  single.struct_ctl:
    type: system.t:single_struct_ctl
    value: {}

  actor_dict.config_ctl:
    type: system.t:dict_config_ctl
    value:
      key_ctl: one_way.key_ctl
      value_ctl: actor.value_ctl
      struct_ctl: single.struct_ctl
