import:
- builtin:type:python_module
- system.t:actor_value_ctl
- system.t:data_value_ctl

definitions:

  config_value_ctl.module:
    type: builtin:type:python_module
    value:
      module_name: config_value_ctl
      file_name: config_value_ctl.dyn.py
      imports:
        pyobj:
          htypes.system.actor_value_ctl: system.t:actor_value_ctl
          htypes.system.data_value_ctl: system.t:data_value_ctl
        raw: {}
