import:
- legacy_type.builtin:attribute
- legacy_type.builtin:record_mt
- legacy_type.cfg_item:data_cfg_item
- legacy_type.model:index_list_ui_t
- legacy_type.model:key_list_ui_t
- legacy_type.system:item_list_config
- legacy_type.system:system_config
- legacy_type.system_fn:ctx_fn
- legacy_type.view_factory:multi_template
- views.details:details.module

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        view_factory_reg: view_factory_reg.config

  view_factory_reg.config:
    type: legacy_type.system:item_list_config
    value:
      items:
      - details.index_list.view-factory-cfg-item
      - details.key_list.view-factory-cfg-item

  details_command_list:
    type: legacy_type.builtin:attribute
    value:
      object: views.details:details.module
      attr_name: details_command_list

  details_command_list.system-fn:
    type: legacy_type.system_fn:ctx_fn
    value:
      function: details_command_list
      ctx_params:
      - model
      - model_state
      - ctx
      service_params:
      - details_commands

  details_get:
    type: legacy_type.builtin:attribute
    value:
      object: views.details:details.module
      attr_name: details_get

  details_get.system-fn:
    type: legacy_type.system_fn:ctx_fn
    value:
      function: details_get
      ctx_params:
      - k
      - model
      - model_state
      - ctx
      service_params:
      - error_view
      - command_creg
      - visualizer

  details_k:
    type: legacy_type.builtin:record_mt
    value:
      module_name: details
      name: details_k
      base: null
      fields: {}

  details.k:
    type: details_k
    value: {}

  details.index_list.view-factory-template:
    type: legacy_type.view_factory:multi_template
    value:
      model_t_list: null
      ui_t_t: legacy_type.model:index_list_ui_t
      list_fn: details_command_list.system-fn
      get_fn: details_get.system-fn

  details.index_list.view-factory-cfg-item:
    type: legacy_type.cfg_item:data_cfg_item
    value:
      key: details.k
      value: details.index_list.view-factory-template

  details.key_list.view-factory-template:
    type: legacy_type.view_factory:multi_template
    value:
      model_t_list: null
      ui_t_t: legacy_type.model:key_list_ui_t
      list_fn: details_command_list.system-fn
      get_fn: details_get.system-fn

  details.key_list.view-factory-cfg-item:
    type: legacy_type.cfg_item:data_cfg_item
    value:
      key: details.k
      value: details.key_list.view-factory-template
