import:
- legacy_type.builtin:python_module

definitions:

  config_ctl.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_ctl
      file_name: config_ctl.dyn.py
      import_list: {}
