import:
- builtins:mosaic.service
- legacy_type.builtin:python_module
- legacy_type.system:item_dict_config_ctl
- legacy_type.system:item_list_config

definitions:

  config_ctl.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_ctl
      file_name: config_ctl.dyn.py
      import_list:
        htypes.system.item_dict_config_ctl: legacy_type.system:item_dict_config_ctl
        htypes.system.item_list_config: legacy_type.system:item_list_config
        services.mosaic: builtins:mosaic.service
