import:
- legacy_type.builtin:attribute
- legacy_type.builtin:record_mt
- legacy_type.cfg_item:data_cfg_item
- legacy_type.model:record_ui_t
- legacy_type.system:item_list_config
- legacy_type.system:system_config
- legacy_type.system_fn:ctx_fn
- legacy_type.view_factory:multi_template
- ui.record_field_view_factory:record_field_view_factory.module

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        view_factory_reg: view_factory_reg.config

  view_factory_reg.config:
    type: legacy_type.system:item_list_config
    value:
      items:
      - record_field_list.view-factory-cfg-item

  record_field_list:
    type: legacy_type.builtin:attribute
    value:
      object: ui.record_field_view_factory:record_field_view_factory.module
      attr_name: record_field_list

  record_field_list.system-fn:
    type: legacy_type.system_fn:ctx_fn
    value:
      function: record_field_list
      ctx_params:
      - ui_t
      - system_fn
      - ctx
      service_params:
      - view_factory_reg

  record_field_get:
    type: legacy_type.builtin:attribute
    value:
      object: ui.record_field_view_factory:record_field_view_factory.module
      attr_name: record_field_get

  record_field_get.system-fn:
    type: legacy_type.system_fn:ctx_fn
    value:
      function: record_field_get
      ctx_params:
      - k
      - ctx
      service_params:
      - view_factory_reg

  record_field_k:
    type: legacy_type.builtin:record_mt
    value:
      module_name: record_field_view_factory
      name: record_field_k
      base: null
      fields: {}

  record_field.k:
    type: record_field_k
    value: {}

  record_field_list.view-factory-template:
    type: legacy_type.view_factory:multi_template
    value:
      model_t_list: null
      ui_t_t: legacy_type.model:record_ui_t
      list_fn: record_field_list.system-fn
      get_fn: record_field_get.system-fn

  record_field_list.view-factory-cfg-item:
    type: legacy_type.cfg_item:data_cfg_item
    value:
      key: record_field.k
      value: record_field_list.view-factory-template
