import:
- legacy_type.builtin:string
- legacy_type.system:system_config
- rc.rc:compile_resources.service

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        system:
        - rc.rc:compile_resources.service
