import:
- builtins:web.service
- legacy_type.builtin:attribute
- legacy_type.builtin:python_module
- legacy_type.cfg_item:typed_cfg_item
- legacy_type.config_item_resource:config_item_resource
- legacy_type.config_item_resource:config_item_resource_override
- legacy_type.system:actor_template
- rc.rc_resource:rc_resource.module

definitions:

  config_item_resource.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_item_resource
      file_name: config_item_resource.dyn.py
      import_list:
        htypes.config_item_resource.config_item_resource: legacy_type.config_item_resource:config_item_resource
        htypes.config_item_resource.config_item_resource_override: legacy_type.config_item_resource:config_item_resource_override
        services.web: builtins:web.service
        code.rc_resource: rc.rc_resource:rc_resource.module

  ConfigItemResource:
    type: legacy_type.builtin:attribute
    value:
      object: config_item_resource.module
      attr_name: ConfigItemResource

  ConfigItemResource.from_piece:
    type: legacy_type.builtin:attribute
    value:
      object: ConfigItemResource
      attr_name: from_piece

  ConfigItemResource.from_piece.actor-template:
    type: legacy_type.system:actor_template
    value:
      function: ConfigItemResource.from_piece
      service_params: []

  config_item_resource-config_item_resource.actor-cfg-item:
    type: legacy_type.cfg_item:typed_cfg_item
    value:
      t: legacy_type.config_item_resource:config_item_resource
      value: ConfigItemResource.from_piece.actor-template

  ConfigItemResourceOverride:
    type: legacy_type.builtin:attribute
    value:
      object: config_item_resource.module
      attr_name: ConfigItemResourceOverride

  ConfigItemResourceOverride.from_piece:
    type: legacy_type.builtin:attribute
    value:
      object: ConfigItemResourceOverride
      attr_name: from_piece

  ConfigItemResourceOverride.from_piece.actor-template:
    type: legacy_type.system:actor_template
    value:
      function: ConfigItemResourceOverride.from_piece
      service_params: []

  config_item_resource-config_item_resource_override.actor-cfg-item:
    type: legacy_type.cfg_item:typed_cfg_item
    value:
      t: legacy_type.config_item_resource:config_item_resource_override
      value: ConfigItemResourceOverride.from_piece.actor-template
