import:
- legacy_type.builtin:string
- legacy_type.system:system_config
- rc.rc:compile_resources.service

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        system:
          compile_resources: rc.rc:compile_resources.service

  compile_resources:
    type: legacy_type.builtin:string
    value: compile_resources
