definitions:

  config_fixture_marker.module:
    type: builtin:type:python_module
    value:
      module_name: config_fixture_marker
      file_name: config_fixture_marker.dyn.py
      imports:
        pyobj:
          code.fixture_ctr: rc.fixture_ctr:fixture_ctr.module
        raw: {}

  config_fixture_marker:
    type: builtin:type:attribute
    value:
      object: config_fixture_marker.module
      attr_name: config_fixture_marker

  config_fixture.marker-template:
    type: marker.t:marker_template
    value:
      function: config_fixture_marker
      service_params:
      - ctr_collector

  config_fixture.marker-cfg-item:
    type: base:cfg_item.t:str_cfg_item
    value:
      key: config_fixture
      value: config_fixture.marker-template

  config_template_fixture_marker:
    type: builtin:type:attribute
    value:
      object: config_fixture_marker.module
      attr_name: config_template_fixture_marker

  config_template_fixture.marker-template:
    type: marker.t:marker_template
    value:
      function: config_template_fixture_marker
      service_params:
      - ctr_collector

  config_template_fixture.marker-cfg-item:
    type: base:cfg_item.t:str_cfg_item
    value:
      key: config_template_fixture
      value: config_template_fixture.marker-template
