import:

- legacy_type.builtin:string
- legacy_type.system:item_list_config
- legacy_type.system:system_config

- base.bundler:bundler.service
- base.file_bundle:file_bundle.service
- base.mark:marker_ctl.service
- base.ref_picker:pick_refs.service
- base.ref_picker:ref_picker_cache.service
- base.rpc.rpc_endpoint:cancel_rpc_request_futures.service
- base.rpc.rpc_endpoint:rpc_error_response.actor-template
- base.rpc.rpc_endpoint:rpc_request.actor-template
- base.rpc.rpc_endpoint:rpc_response.actor-template
- base.rpc.rpc_endpoint:rpc_endpoint.service
- base.rpc.rpc_endpoint:rpc_message_creg.service
- base.rpc.rpc_endpoint:rpc_request_futures.service
- base.rpc.rpc_endpoint:rpc_target_creg.service
- base.rpc.rpc_endpoint:rpc_function_target.actor-template
- base.rpc.rpc_endpoint:rpc_service_target.actor-template
- base.rpc.rpc_call:rpc_call_factory.service
- base.rpc.rpc_call:rpc_servant_wrapper.service
- base.rpc.rpc_call:rpc_service_wrapper.service
- base.rpc.rpc_call:rpc_submit_factory.service
- base.rpc.rpc_call:rpc_submit_target_factory.service
- base.rpc.rpc_call:rpc_wait_for_future.service
- base.rpc.rpc_call:service_call_factory.service
- base.rpc.rpc_call:service_submit_factory.service
- base.subprocess.subprocess:subprocess_running.service
- base.subprocess.subprocess_rpc_server:subprocess_rpc_main.service
- base.subprocess.subprocess_rpc_server:subprocess_rpc_server_running.service
- base.subprocess.subprocess_rpc_server_main:rpc_server_main.service
- base.subprocess.subprocess_transport:subprocess_transport.service
- base.system.system_stop:stop_signal.service
- base.system.system_stop:system_failed.service
- base.transport.endpoint:endpoint_registry.service
- base.transport.endpoint:endpoint_thread_pool.service
- base.transport.identity:identity_registry.service
- base.transport.identity:parcel_registry.service
- base.transport.identity:peer_registry.service
- base.transport.identity:signature_registry.service
- base.transport.route_registry:route_registry.service
- base.transport.rsa_identity:generate_rsa_identity.service
- base.transport.rsa_identity:rsa_identity_rsa_identity.actor-template
- base.transport.rsa_identity:rsa_identity_rsa_parcel.actor-template
- base.transport.rsa_identity:rsa_identity_rsa_peer.actor-template
- base.transport.rsa_identity:rsa_identity_rsa_signature.actor-template
- base.transport.sync_route_table:route_table.service
- base.transport.transport:transport.service
- rc.actor_ctr:actor_resource_actor_probe_ctr.actor-template
- rc.actor_ctr:actor_resource_actor_template_ctr.actor-template
- rc.actor_ctr:system_actor_template.actor-template
- rc.actor_marker:actor.marker-template
- rc.actor_probe:actor_resource_actor_probe_template.actor-template
- rc.builtin_service_target:builtin_service_builtin_service_req.actor-template
- rc.cfg_item_req:actor_resource_cfg_item_req.actor-template
- rc.crud_ctr:crud_ctr_commit_ctr.actor-template
- rc.crud_ctr:crud_ctr_init_ctr.actor-template
- rc.crud_marker:crud.marker-template
- rc.ctr_collector:ctr_collector_ignore_module_cfg_item.actor-template
- rc.ctr_collector:ctr_collector_mark_module_cfg_item.actor-template
- rc.ctr_collector:ctr_collector.service
- rc.command_ctr:command_resource_global_model_command_template_ctr.actor-template
- rc.command_ctr:command_resource_model_command_template_ctr.actor-template
- rc.command_ctr:command_resource_model_command_enumerator_template_ctr.actor-template
- rc.command_ctr:command_resource_ui_command_template_ctr.actor-template
- rc.command_ctr:command_resource_universal_ui_command_template_ctr.actor-template
- rc.command_marker:command.marker-template
- rc.command_marker:command_enum.marker-template
- rc.command_marker:global_command.marker-template
- rc.command_marker:ui_command.marker-template
- rc.command_marker:universal_ui_command.marker-template
- rc.command_marker:ui_model_command.marker-template
- rc.config_fixture_marker:config_fixture.marker-template
- rc.config_item_resource:config_item_resource_config_item_resource.actor-template
- rc.config_item_resource:config_item_resource_config_item_resource_override.actor-template
- rc.feed_ctr:feed_list_feed_ctr.actor-template
- rc.feed_ctr:feed_index_tree_feed_ctr.actor-template
- rc.import_job:import_job_failed_result.actor-template
- rc.import_job:import_job_incomplete_result.actor-template
- rc.import_job:import_job_job.actor-template
- rc.import_job:import_job_succeeded_result.actor-template
- rc.import_recorder:import_recorder_import_recorder.actor-template
- rc.import_recorder:import_recorder_reg.service
- rc.import_record_cfg_item:import_resource_import_resource.actor-template
- rc.import_resource:import_resource_import_resource.actor-template
- rc.init_targets:ctr_from_template_creg.service
- rc.fixture_ctr:fixture_resource_config_fixture_ctr.actor-template
- rc.fixture_ctr:fixture_resource_fixture_obj_ctr.actor-template
- rc.fixture_ctr:fixture_resource_fixture_probe_ctr.actor-template
- rc.fixture_marker:fixture.marker-template
- rc.fixture_resource:fixture_resource_config_fixture_resource.actor-template
- rc.fixture_probe:fixture_resource_fixture_obj_template.actor-template
- rc.fixture_probe:fixture_resource_fixture_probe_template.actor-template
- rc.job_cache:job_cache.service
- rc.marker_ctr:marker_marker_template.actor-template
- rc.marker_registry:marker_marker_template.actor-template
- rc.marker_registry:marker_registry.service
- rc.model_ctr:model_resource_model_ctr.actor-template
- rc.model_marker:model.marker-template
- rc.rc_constructor_creg:rc_constructor_creg.service
- rc.rc_job:rc_job_submit_factory.service
- rc.rc_job:rc_job_job_target.actor-template
- rc.rc_job_creg:rc_job_creg.service
- rc.rc_job_result_creg:rc_job_result_creg.service
- rc.rc:compile_resources.service
- rc.rc:rc_main.service
- rc.rc_requirement_creg:rc_requirement_creg.service
- rc.rc_resource_creg:rc_resource_creg.service
- rc.process_pool:process_pool_running.service
- rc.python_module_resource_target:python_module_resource_target_import_python_module_req.actor-template
- rc.python_module_resource_target:python_module_resource_target_python_module_req.actor-template
- rc.selector_ctr:selector_ctr_get_ctr.actor-template
- rc.selector_ctr:selector_ctr_pick_ctr.actor-template
- rc.selector_marker:selector.marker-template
- rc.service_ctr:service_resource_finalizer_gen_service_template_ctr.actor-template
- rc.service_ctr:service_resource_service_template_ctr.actor-template
- rc.service_ctr:system_finalizer_gen_service_template.actor-template
- rc.service_ctr:system_service_template.actor-template
- rc.service_probe_resource:service_resource_service_probe_ctr.actor-template
- rc.service_marker:service.marker-template
- rc.service_probe_resource:service_resource_service_probe_template.actor-template
- rc.service_req:service_resource_service_req.actor-template
- rc.test_job:test_job_failed_result.actor-template
- rc.test_job:test_job_incomplete_result.actor-template
- rc.test_job:test_job_succeeded_result.actor-template
- rc.test_job:test_job_job.actor-template
- rc.test_job:test_job_rpc_service_wrapper.service
- rc.test_module_resources_req:test_module_resources_req_test_module_resources_req.actor-template
- rc.test_requirement:test_target_fixtures_module_req.actor-template
- rc.test_requirement:test_target_recorder_resource.actor-template
- rc.test_requirement:test_target_tested_code_req.actor-template
- rc.test_requirement:test_target_tested_code_resource.actor-template
- rc.type_req:type_resource_type_req.actor-template
- rc.view_ctr:view_ctr_template_ctr.actor-template
- rc.view_factory_ctr:view_factory_ctr_ctr.actor-template
- rc.view_factory_marker:view_factory.marker-template
- rc.view_marker:view.marker-template
- resource.data_to_pyobj:data_to_pyobj_ref.service
- resource.data_to_pyobj:data_to_pyobj.service
- resource.partial_ref:partial_ref.service

definitions:

  system:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.bundler:bundler.service
      - base.file_bundle:file_bundle.service
      - base.mark:marker_ctl.service
      - base.ref_picker:pick_refs.service
      - base.ref_picker:ref_picker_cache.service
      - base.rpc.rpc_endpoint:cancel_rpc_request_futures.service
      - base.rpc.rpc_endpoint:rpc_target_creg.service
      - base.rpc.rpc_endpoint:rpc_message_creg.service
      - base.rpc.rpc_endpoint:rpc_endpoint.service
      - base.rpc.rpc_endpoint:rpc_request_futures.service
      - base.rpc.rpc_call:rpc_submit_target_factory.service
      - base.rpc.rpc_call:rpc_servant_wrapper.service
      - base.rpc.rpc_call:rpc_service_wrapper.service
      - base.rpc.rpc_call:rpc_submit_factory.service
      - base.rpc.rpc_call:service_submit_factory.service
      - base.rpc.rpc_call:rpc_wait_for_future.service
      - base.rpc.rpc_call:rpc_call_factory.service
      - base.rpc.rpc_call:service_call_factory.service
      - base.subprocess.subprocess:subprocess_running.service
      - base.subprocess.subprocess_rpc_server:subprocess_rpc_main.service
      - base.subprocess.subprocess_rpc_server:subprocess_rpc_server_running.service
      - base.subprocess.subprocess_rpc_server_main:rpc_server_main.service
      - base.subprocess.subprocess_transport:subprocess_transport.service
      - base.system.system_stop:stop_signal.service
      - base.system.system_stop:system_failed.service
      - base.transport.endpoint:endpoint_thread_pool.service
      - base.transport.endpoint:endpoint_registry.service
      - base.transport.identity:identity_registry.service
      - base.transport.identity:parcel_registry.service
      - base.transport.identity:peer_registry.service
      - base.transport.identity:signature_registry.service
      - base.transport.route_registry:route_registry.service
      - base.transport.rsa_identity:generate_rsa_identity.service
      - base.transport.sync_route_table:route_table.service
      - base.transport.transport:transport.service
      - rc.ctr_collector:ctr_collector.service
      - rc.import_recorder:import_recorder_reg.service
      - rc.init_targets:ctr_from_template_creg.service
      - rc.job_cache:job_cache.service
      - rc.marker_registry:marker_registry.service
      - rc.rc_constructor_creg:rc_constructor_creg.service
      - rc.rc_job:rc_job_submit_factory.service
      - rc.rc_job_creg:rc_job_creg.service
      - rc.rc_job_result_creg:rc_job_result_creg.service
      - rc.rc:compile_resources.service
      - rc.rc:rc_main.service
      - rc.rc_requirement_creg:rc_requirement_creg.service
      - rc.rc_resource_creg:rc_resource_creg.service
      - rc.process_pool:process_pool_running.service
      - rc.test_job:test_job_rpc_service_wrapper.service
      - resource.data_to_pyobj:data_to_pyobj_ref.service
      - resource.data_to_pyobj:data_to_pyobj.service
      - resource.partial_ref:partial_ref.service

  cfg_item_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.marker_registry:marker_marker_template.actor-template
      - rc.actor_probe:actor_resource_actor_probe_template.actor-template
      - rc.ctr_collector:ctr_collector_mark_module_cfg_item.actor-template
      - rc.ctr_collector:ctr_collector_ignore_module_cfg_item.actor-template
      - rc.fixture_probe:fixture_resource_fixture_obj_template.actor-template
      - rc.fixture_probe:fixture_resource_fixture_probe_template.actor-template
      - rc.import_record_cfg_item:import_resource_import_resource.actor-template
      - rc.service_probe_resource:service_resource_service_probe_template.actor-template

  ctr_from_template_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.service_ctr:system_service_template.actor-template
      - rc.service_ctr:system_finalizer_gen_service_template.actor-template
      - rc.actor_ctr:system_actor_template.actor-template
      - rc.marker_ctr:marker_marker_template.actor-template

  identity_registry:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.transport.rsa_identity:rsa_identity_rsa_identity.actor-template

  marker_registry:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.actor_marker:actor.marker-template
      - rc.command_marker:command.marker-template
      - rc.command_marker:command_enum.marker-template
      - rc.command_marker:global_command.marker-template
      - rc.command_marker:ui_command.marker-template
      - rc.command_marker:universal_ui_command.marker-template
      - rc.command_marker:ui_model_command.marker-template
      - rc.config_fixture_marker:config_fixture.marker-template
      - rc.crud_marker:crud.marker-template
      - rc.fixture_marker:fixture.marker-template
      - rc.model_marker:model.marker-template
      - rc.selector_marker:selector.marker-template
      - rc.service_marker:service.marker-template
      - rc.view_factory_marker:view_factory.marker-template
      - rc.view_marker:view.marker-template

  parcel_registry:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.transport.rsa_identity:rsa_identity_rsa_parcel.actor-template

  peer_registry:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.transport.rsa_identity:rsa_identity_rsa_peer.actor-template

  pyobj_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.import_recorder:import_recorder_import_recorder.actor-template

  rpc_message_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.rpc.rpc_endpoint:rpc_request.actor-template
      - base.rpc.rpc_endpoint:rpc_response.actor-template
      - base.rpc.rpc_endpoint:rpc_error_response.actor-template

  rpc_target_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.rpc.rpc_endpoint:rpc_function_target.actor-template
      - base.rpc.rpc_endpoint:rpc_service_target.actor-template
      - rc.rc_job:rc_job_job_target.actor-template

  rc_constructor_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.actor_ctr:actor_resource_actor_probe_ctr.actor-template
      - rc.actor_ctr:actor_resource_actor_template_ctr.actor-template
      - rc.command_ctr:command_resource_global_model_command_template_ctr.actor-template
      - rc.command_ctr:command_resource_model_command_template_ctr.actor-template
      - rc.command_ctr:command_resource_model_command_enumerator_template_ctr.actor-template
      - rc.command_ctr:command_resource_ui_command_template_ctr.actor-template
      - rc.command_ctr:command_resource_universal_ui_command_template_ctr.actor-template
      - rc.crud_ctr:crud_ctr_commit_ctr.actor-template
      - rc.crud_ctr:crud_ctr_init_ctr.actor-template
      - rc.feed_ctr:feed_list_feed_ctr.actor-template
      - rc.feed_ctr:feed_index_tree_feed_ctr.actor-template
      - rc.fixture_ctr:fixture_resource_config_fixture_ctr.actor-template
      - rc.fixture_ctr:fixture_resource_fixture_obj_ctr.actor-template
      - rc.fixture_ctr:fixture_resource_fixture_probe_ctr.actor-template
      - rc.model_ctr:model_resource_model_ctr.actor-template
      - rc.selector_ctr:selector_ctr_get_ctr.actor-template
      - rc.selector_ctr:selector_ctr_pick_ctr.actor-template
      - rc.service_ctr:service_resource_finalizer_gen_service_template_ctr.actor-template
      - rc.service_ctr:service_resource_service_template_ctr.actor-template
      - rc.service_probe_resource:service_resource_service_probe_ctr.actor-template
      - rc.view_ctr:view_ctr_template_ctr.actor-template
      - rc.view_factory_ctr:view_factory_ctr_ctr.actor-template

  rc_job_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.import_job:import_job_job.actor-template
      - rc.test_job:test_job_job.actor-template

  rc_job_result_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.import_job:import_job_succeeded_result.actor-template
      - rc.import_job:import_job_incomplete_result.actor-template
      - rc.import_job:import_job_failed_result.actor-template
      - rc.test_job:test_job_succeeded_result.actor-template
      - rc.test_job:test_job_incomplete_result.actor-template
      - rc.test_job:test_job_failed_result.actor-template

  rc_requirement_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.builtin_service_target:builtin_service_builtin_service_req.actor-template
      - rc.cfg_item_req:actor_resource_cfg_item_req.actor-template
      - rc.python_module_resource_target:python_module_resource_target_import_python_module_req.actor-template
      - rc.python_module_resource_target:python_module_resource_target_python_module_req.actor-template
      - rc.service_req:service_resource_service_req.actor-template
      - rc.test_module_resources_req:test_module_resources_req_test_module_resources_req.actor-template
      - rc.test_requirement:test_target_tested_code_req.actor-template
      - rc.test_requirement:test_target_fixtures_module_req.actor-template
      - rc.type_req:type_resource_type_req.actor-template

  rc_resource_creg:
    type: legacy_type.system:item_list_config
    value:
      items:
      - rc.import_resource:import_resource_import_resource.actor-template
      - rc.fixture_resource:fixture_resource_config_fixture_resource.actor-template
      - rc.config_item_resource:config_item_resource_config_item_resource.actor-template
      - rc.config_item_resource:config_item_resource_config_item_resource_override.actor-template
      - rc.test_requirement:test_target_tested_code_resource.actor-template
      - rc.test_requirement:test_target_recorder_resource.actor-template

  signature_registry:
    type: legacy_type.system:item_list_config
    value:
      items:
      - base.transport.rsa_identity:rsa_identity_rsa_signature.actor-template

  config:
    type: legacy_type.system:system_config
    value:
      services:
        system: system
        cfg_item_creg: cfg_item_creg
        ctr_from_template_creg: ctr_from_template_creg
        identity_registry: identity_registry
        marker_registry: marker_registry
        parcel_registry: parcel_registry
        peer_registry: peer_registry
        pyobj_creg: pyobj_creg
        rpc_message_creg: rpc_message_creg
        rpc_target_creg: rpc_target_creg
        rc_constructor_creg: rc_constructor_creg
        rc_job_creg: rc_job_creg
        rc_job_result_creg: rc_job_result_creg
        rc_requirement_creg: rc_requirement_creg
        rc_resource_creg: rc_resource_creg
        signature_registry: signature_registry
