definitions:

  config:
    type: base:system/system.t:system_config
    value:
      services:
        base:system/system:service_config_creg.service: service_config_creg.config
        base:system/system:service_creg.service: service_creg.config

  service_config_creg.config:
    type: base:system/system.t:data_item_list
    value:
      items: {}

  service_creg.config:
    type: base:system/system.t:data_item_list
    value:
      items:
        main:compile_resources.service: main:compile_resources.actor
        main:main.service: main:main.actor
