definitions:

  config_item_target.module:
    type: builtin:type:python_module
    value:
      module_name: config_item_target
      file_name: config_item_target.dyn.py
      imports:
        pyobj:
          code.rc_target: rc.rc_target:rc_target.module
        raw: {}
