definitions:

  config_resource_target.module:
    type: builtin:type:python_module
    value:
      module_name: config_resource_target
      file_name: config_resource_target.dyn.py
      imports:
        pyobj:
          services.mosaic: builtins:mosaic.service
          services.resource_module_factory: builtins:resource_module_factory.service
          # code.config_ctl: base.system.config_ctl:config_ctl.module
          code.config_item_resource: config_item_resource:config_item_resource.module
          code.rc_target: rc_target:rc_target.module
        raw: {}
