import:
- legacy_type.builtin:string
- legacy_type.system:system_config
- common.bundler:bundler.service
- rc.actor_ctr:core-actor-from-template.actor-template
- rc.init_targets:ctr_from_template_creg.service
- rc.rc:compile_resources.service
- rc.process_pool:process_pool_running.service
- rc.service_ctr:core-service-from-finalizer-gen-template.actor-template
- rc.service_ctr:core-service-from-template.actor-template
- rpc.rpc_endpoint:on_rpc_error_response.actor-template
- rpc.rpc_endpoint:on_rpc_request.actor-template
- rpc.rpc_endpoint:on_rpc_response.actor-template
- rpc.rpc_endpoint:rpc_endpoint.service
- rpc.rpc_endpoint:rpc_message_creg.service
- rpc.rpc_endpoint:rpc_request_futures.service
- rpc.rpc_endpoint:rpc_target_creg.service
- rpc.rpc_endpoint:run_function_target.actor-template
- rpc.rpc_call:rpc_call_factory.service
- rpc.rpc_call:rpc_submit_factory.service
- subprocess.subprocess:subprocess_running.service
- subprocess.subprocess_rpc_server:subprocess_rpc_server_running.service
- subprocess.subprocess_rpc_server_main:rpc_server_main.service
- subprocess.subprocess_transport:subprocess_transport.service
- transport.endpoint:endpoint_registry.service
- transport.endpoint:endpoint_thread_pool.service
- transport.identity:identity_registry.service
- transport.identity:parcel_registry.service
- transport.identity:peer_registry.service
- transport.identity:signature_registry.service
- transport.route_registry:route_registry.service
- transport.rsa_identity:generate_rsa_identity.service
- transport.rsa_identity:rsa_parcel.actor-template
- transport.rsa_identity:rsa_peer.actor-template
- transport.rsa_identity:rsa_signature.actor-template
- transport.sync_route_table:route_table.service
- transport.transport:transport.service

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        system:
        - common.bundler:bundler.service
        - rc.init_targets:ctr_from_template_creg.service
        - rc.rc:compile_resources.service
        - rc.process_pool:process_pool_running.service
        - rpc.rpc_endpoint:rpc_target_creg.service
        - rpc.rpc_endpoint:rpc_message_creg.service
        - rpc.rpc_endpoint:rpc_endpoint.service
        - rpc.rpc_endpoint:rpc_request_futures.service
        - rpc.rpc_call:rpc_call_factory.service
        - rpc.rpc_call:rpc_submit_factory.service
        - subprocess.subprocess:subprocess_running.service
        - subprocess.subprocess_rpc_server:subprocess_rpc_server_running.service
        - subprocess.subprocess_rpc_server_main:rpc_server_main.service
        - subprocess.subprocess_transport:subprocess_transport.service
        - transport.endpoint:endpoint_thread_pool.service
        - transport.endpoint:endpoint_registry.service
        - transport.identity:identity_registry.service
        - transport.identity:parcel_registry.service
        - transport.identity:peer_registry.service
        - transport.identity:signature_registry.service
        - transport.route_registry:route_registry.service
        - transport.rsa_identity:generate_rsa_identity.service
        - transport.sync_route_table:route_table.service
        - transport.transport:transport.service
        ctr_from_template_creg:
        - rc.service_ctr:core-service-from-template.actor-template
        - rc.service_ctr:core-service-from-finalizer-gen-template.actor-template
        - rc.actor_ctr:core-actor-from-template.actor-template
        peer_registry:
        - transport.rsa_identity:rsa_peer.actor-template
        parcel_registry:
        - transport.rsa_identity:rsa_parcel.actor-template
        signature_registry:
        - transport.rsa_identity:rsa_signature.actor-template
        rpc_message_creg:
        - rpc.rpc_endpoint:on_rpc_request.actor-template
        - rpc.rpc_endpoint:on_rpc_response.actor-template
        - rpc.rpc_endpoint:on_rpc_error_response.actor-template
        rpc_target_creg:
        - rpc.rpc_endpoint:run_function_target.actor-template
