definitions:

  data_config_ctr.module:
    type: builtin:type:python_module
    value:
      module_name: data_config_ctr
      file_name: data_config_ctr.dyn.py
      imports:
        pyobj:
          htypes.cfg_item.data_cfg_item: base:cfg_item.t:data_cfg_item
          services.mosaic: builtins:mosaic.service
          code.cfg_item_req: rc.cfg_item_req:cfg_item_req.module
          code.rc_constructor: rc.rc_constructor:rc_constructor.module
          code.config_item_resource: rc.config_item_resource:config_item_resource.module
        raw: {}
