import:
- client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
- client.lcs_storage_shortcuts:shortcut_I
- legacy_type.builtin:record_mt
- legacy_type.builtin:string
- legacy_type.command:custom_model_command_list
- legacy_type.command:custom_model_commands_lcs_d
- legacy_type.command:custom_ui_command
- legacy_type.identity_command:identity_command
- legacy_type.lcs_resource_storage:mapping
- legacy_type.sample_list:open_feed_sample_fn_list_d
- legacy_type.sample_list:open_sample_fn_list_d
- legacy_type.sample_list:sample_list
definitions:
  custom_model_command_list_1:
    type: legacy_type.command:custom_model_command_list
    value:
      commands:
      - custom_ui_command_1
  custom_model_commands_lcs_d_1:
    type: legacy_type.command:custom_model_commands_lcs_d
    value: {}
  custom_ui_command_1:
    type: legacy_type.command:custom_ui_command
    value:
      ui_command_d: identity_d_1
      model_command: identity_command_1
      layout: null
  identity_command_1:
    type: legacy_type.identity_command:identity_command
    value:
      d: identity_d_1
  identity_d:
    type: legacy_type.builtin:record_mt
    value:
      module_name: custom_command
      name: identity_d
      base: null
      fields: {}
  identity_d_1:
    type: identity_d
    value: {}
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - custom_model_commands_lcs_d_1
        - legacy_type.sample_list:sample_list
        value: custom_model_command_list_1
      - key:
        - open_sample_fn_list_d_1
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_F4
      - key:
        - open_feed_sample_fn_list_d_1
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_F5
      - key:
        - identity_d_1
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: client.lcs_storage_shortcuts:shortcut_I
  open_feed_sample_fn_list_d_1:
    type: legacy_type.sample_list:open_feed_sample_fn_list_d
    value: {}
  open_sample_fn_list_d_1:
    type: legacy_type.sample_list:open_sample_fn_list_d
    value: {}
  shortcut_F4:
    type: legacy_type.builtin:string
    value: F4
  shortcut_F5:
    type: legacy_type.builtin:string
    value: F5
