definitions:

  config_ctl.module:
    type: builtin:type:python_module
    value:
      module_name: config_ctl
      file_name: config_ctl.dyn.py
      imports:
        pyobj:
          htypes.system.dict_config_ctl: :system/system.t:dict_config_ctl
          htypes.system.flat_list_config_ctl: :system/system.t:flat_list_config_ctl
          htypes.system.item_list_config: :system/system.t:item_list_config
          htypes.system.service_config: :system/system.t:service_config
          htypes.system.system_config: :system/system.t:system_config
          services.mosaic: builtin:service:mosaic
          services.web: builtin:service:web
        raw: {}

  FlatListConfigCtl:
    type: builtin:type:attribute
    value:
      object: config_ctl.module
      attr_name: FlatListConfigCtl

  FlatListConfigCtl.from_piece:
    type: builtin:type:attribute
    value:
      object: FlatListConfigCtl
      attr_name: from_piece

  FlatListConfigCtl.from_piece.actor-template:
    type: :system/system.t:actor_template
    value:
      function: FlatListConfigCtl.from_piece
      service_params:
      - cfg_item_creg
      - cfg_value_creg

  config_ctl_creg-system-flat_list_config_ctl.actor-cfg-item:
    type: :cfg_item.t:type_cfg_item
    value:
      t: :system/system.t:flat_list_config_ctl
      value: FlatListConfigCtl.from_piece.actor-template

  data_key.ctl:
    type: :system/system.t:data_key_ctl
    value: {}

  data_value.ctl:
    type: :system/system.t:data_value_ctl
    value: {}

  single.struct_ctl:
    type: :system/system.t:single_struct_ctl
    value: {}

  data_service_config.ctl:
    type: :system/system.t:dict_config_ctl
    value:
      key_ctl: data_key.ctl
      value_ctl: data_value.ctl
      struct_ctl: single.struct_ctl
