definitions:

  config_item_ctl.module:
    type: builtin:type:python_module
    value:
      module_name: config_item_ctl
      file_name: config_item_ctl.dyn.py
      imports:
        pyobj:
          htypes.cfg_item.data_cfg_item: :cfg_item.t:data_cfg_item
          htypes.cfg_item.str_cfg_item: :cfg_item.t:str_cfg_item
          htypes.cfg_item.type_cfg_item: :cfg_item.t:type_cfg_item
          htypes.config_ctl.data_key_ctl: config_ctl.t:data_key_ctl
          htypes.config_ctl.str_key_ctl: config_ctl.t:str_key_ctl
          htypes.config_ctl.type_key_ctl: config_ctl.t:type_key_ctl
          services.mosaic: builtin:service:mosaic
          services.pyobj_creg: builtin:service:pyobj_creg
          services.web: builtin:service:web
        raw: {}

  # data_cfg_item_builtin:type:type:attribute
  #   value:
  #     object: config_item_ctl.module
  #     attr_name: data_cfg_item_name

  # data_cfg_item_name.actor-template:
  #   type: :system/system.t:actor_  #     function.t: data_cfg_item_name
  #     service_params: []

  # resource_name_creg-cfg_item-data_cfg_item.actor-cfg-item:
  #   type: :cfg_item.t:type_cfg_item
  #   value:
  #     t: :cfg_item.t:data_cfg_item
  #     value: data_cfg_item_name.actor-template
