import:
- builtin:service:mosaic
- builtin:service:pyobj_creg
- builtins:web.service
- builtin:type:attribute
- builtin:type:python_module
- legacy_type.cfg_item:data_cfg_item
- legacy_type.cfg_item:str_cfg_item
- legacy_type.cfg_item:type_cfg_item
# - legacy_type.system:actor_template
- legacy_type.config_ctl:data_key_ctl
- legacy_type.config_ctl:str_key_ctl
- legacy_type.config_ctl:type_key_ctl

definitions:

  config_item_ctl.module:
    type: builtin:type:python_module
    value:
      module_name: config_item_ctl
      file_name: config_item_ctl.dyn.py
      imports:
        pyobj:
          htypes.cfg_item.data_cfg_item: legacy_type.cfg_item:data_cfg_item
          htypes.cfg_item.str_cfg_item: legacy_type.cfg_item:str_cfg_item
          htypes.cfg_item.type_cfg_item: legacy_type.cfg_item:type_cfg_item
          htypes.config_ctl.data_key_ctl: legacy_type.config_ctl:data_key_ctl
          htypes.config_ctl.str_key_ctl: legacy_type.config_ctl:str_key_ctl
          htypes.config_ctl.type_key_ctl: legacy_type.config_ctl:type_key_ctl
          services.mosaic: builtin:service:mosaic
          services.pyobj_creg: builtin:service:pyobj_creg
          services.web: builtins:web.service
        raw: {}

  # data_cfg_item_builtin:type:type:attribute
  #   value:
  #     object: config_item_ctl.module
  #     attr_name: data_cfg_item_name

  # data_cfg_item_name.actor-template:
  #   type: legacy_type.system:actor_  #     function.t: data_cfg_item_name
  #     service_params: []

  # resource_name_creg-cfg_item-data_cfg_item.actor-cfg-item:
  #   type: legacy_type.cfg_item:type_cfg_item
  #   value:
  #     t: legacy_type.cfg_item:data_cfg_item
  #     value: data_cfg_item_name.actor-template
