import:
- client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
- client.lcs_storage_shortcuts:shortcut_Alt_W
- lcs.lcs_dirs_view:lcs_dirs_items.d
- lcs.lcs_dirs_view:lcs_open_dirs.d
- lcs.lcs_view:lcs_remove.d
- lcs.lcs_view:open_lcs_view.d
- legacy_type.builtin:bool
- legacy_type.builtin:string
- legacy_type.column:column_d
- legacy_type.column:list_d
- legacy_type.column:show_d
- legacy_type.lcs_dirs_view:view
- legacy_type.lcs_resource_storage:mapping
- legacy_type.lcs_view:view
definitions:
  bool_1:
    type: legacy_type.builtin:bool
    value: false
  column_d_1:
    type: legacy_type.column:column_d
    value:
      name: layer_d
  column_d_2:
    type: legacy_type.column:column_d
    value:
      name: dir
  column_d_3:
    type: legacy_type.column:column_d
    value:
      name: piece
  column_d_4:
    type: legacy_type.column:column_d
    value:
      name: d
  lcs_storage_mapping:
    type: legacy_type.lcs_resource_storage:mapping
    value:
      elements:
      - key:
        - legacy_type.lcs_view:view
        - show_d_1
        - list_d_1
        - column_d_1
        value: bool_1
      - key:
        - legacy_type.lcs_view:view
        - show_d_1
        - list_d_1
        - column_d_2
        value: bool_1
      - key:
        - legacy_type.lcs_view:view
        - show_d_1
        - list_d_1
        - column_d_3
        value: bool_1
      - key:
        - show_d_1
        - list_d_1
        - legacy_type.lcs_dirs_view:view
        - column_d_4
        value: bool_1
      - key:
        - lcs.lcs_dirs_view:lcs_open_dirs.d
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_D
      - key:
        - lcs.lcs_dirs_view:lcs_dirs_items.d
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: client.lcs_storage_shortcuts:shortcut_Alt_W
      - key:
        - lcs.lcs_view:lcs_remove.d
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_Del
      - key:
        - lcs.lcs_view:open_lcs_view.d
        - client.lcs_storage_shortcuts:command_shortcut_lcs_d_1
        value: shortcut_Alt_L
  list_d_1:
    type: legacy_type.column:list_d
    value: {}
  shortcut_Alt_L:
    type: legacy_type.builtin:string
    value: Alt+L
  shortcut_D:
    type: legacy_type.builtin:string
    value: D
  shortcut_Del:
    type: legacy_type.builtin:string
    value: Del
  show_d_1:
    type: legacy_type.column:show_d
    value: {}
