import:
  types:
    layered_config_sheet:
      - lcs_storage
      - lcs_association
  code:
    - async.ui.module
require:
  - file_bundle
  - aux_bundler_hooks
  - aux_unbundler_hooks
  - meta_registry
provide:
  - lcs
