
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BD736956F6E173F41189F40EB0E6E50B'
    
_lr_action_items = {'NAME':([2,8,9,],[5,5,12,]),'ENCODING':([0,],[2,]),'EQUAL':([5,],[9,]),'ENDMARKER':([3,4,8,10,12,13,],[7,-5,11,-4,-7,-6,]),'NEWLINE':([3,4,10,12,13,],[8,-5,-4,-7,-6,]),'$end':([1,6,7,11,],[0,-1,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'typedef_list':([2,],[3,]),'typedef':([2,8,],[4,10,]),'module':([0,],[1,]),'type_expr':([9,],[13,]),'eom':([3,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> ENCODING typedef_list eom','module',3,'p_module_1','type_module_parser.py',25),
  ('eom -> NEWLINE ENDMARKER','eom',2,'p_eom_1','type_module_parser.py',29),
  ('eom -> ENDMARKER','eom',1,'p_eom_2','type_module_parser.py',32),
  ('typedef_list -> typedef_list NEWLINE typedef','typedef_list',3,'p_typedef_list_multi','type_module_parser.py',35),
  ('typedef_list -> typedef','typedef_list',1,'p_typedef_list_single','type_module_parser.py',39),
  ('typedef -> NAME EQUAL type_expr','typedef',3,'p_typedef','type_module_parser.py',43),
  ('type_expr -> NAME','type_expr',1,'p_type_expr_name','type_module_parser.py',47),
]
