base:
rc:
  imports: [base]
common:
  imports: [base]
ui:
  imports: [base, common, rc]
models:
  imports: [base, common, ui]
lcs:
  imports: [base, common, ui, models]
views:
  # TODO: May be remove models, it is used by command_layout_context module.
  imports: [base, common, ui, models]
sample:
  imports: [base, common, ui]
server:
  imports: [base, common, ui]
client:
  imports: [base, common, ui, sample, lcs]
