import:
  types:
    object:
      - object_d
    view:
      - view_d
    command_list:
      - object_command_list
    dir_list:
      - dir_list
    selector:
      - selector
    available_view_list:
      - available_view_list
    view_selector:
      - view_selector
    object_view_config:
      - object_view_config_d
      - object_view_config
  code:
    - async.ui.command
    - async.ui.record_object
require:
  - lcs
  - async_web
  - object_factory
  - view_producer
  - view_dir_to_config
  - make_selector_callback_ref
