import:
  types:
    record_object:
      - record_object_d
    view:
      - view_d
    command_list:
      - object_command_list
    record_field_list:
      - record_field_list
    record_view_config:
      - record_view_config_d
      - record_view_config
  code:
    - async.ui.command
    - async.ui.object_view_config
require:
  - lcs
  - async_web
  - object_factory
  - view_producer
  - view_dir_to_config
