Application:
  commands:
    open_server:
      text: Open server
      description: Load server url from file
      shortcuts:
      - Alt+O
    quit:
      text: Quit
      description: Quit application
      shortcuts:
      - Alt+Q
