
import:
- client.client:client_async_main.service
- client.client:client_main.service
- legacy_type.system:item_list_config
- legacy_type.system:system_config

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        system: system

  system:
    type: legacy_type.system:item_list_config
    value:
      items:
      - client.client:client_async_main.service
      - client.client:client_main.service
